### ISSUE TITLE
ToDo list: Missing templates for responses 

### ISSUE THREAD

**Issue by toxyl** [toxyl/ossh#1]
- [ ] `unset`
- [ ] `export`
- [x] `nvidia-smi`
- [x] `ip`
- [x] `ifconfigcloud`
- [x] `sed`
- [ ] `python3`
- [ ] `yum`
- [ ] `crontab -r` 
- [x] `./.senpai.loader`
- [x] `./23`
- [x] `./23s`
- [ ] `./awoo`
- [ ] `./lan`
- [ ] `./ok.sh`
- [x] `./sh`
- [x] `./x86_64`
- [ ] `./sc.sh`
- [ ] `PATH=/dev/shm/:/tmp/:./:/var/tmp/:/root/:/etc/:$PATH`
- [ ] `PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`
- [x] `#!/bin/sh`
- [ ] ` `  (really, an empty string, maybe a line break?)
- [ ] `>/var/log/lastlog`
- [ ] `>/var/log/wtmp`
- [ ] `>/var/log/btmp`

**Comment by dylandreimerink** [comment]
If we encounter a `./` I think we should check the FS for the given file #6.

Perhaps some other additions to this list which I have seen:
- [x] uname -a
- [x] nproc

**Comment by toxyl** [comment]
agreed @ `./`

> * [ ]  uname -a
> * [ ]  nproc

`nproc` is already handled: https://github.com/Toxyl/ossh/blob/master/config.example.yaml#L47
And `uname -a` as well: https://github.com/Toxyl/ossh/blob/master/config.example.yaml#L37
